// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sucpuwbwjmxkbqcllfrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Y3B1d2J3am14a2JxY2xsZnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MjgyMDQsImV4cCI6MjA3OTAwNDIwNH0.akhng3iWLO4SZRbErLPLLJN3cf9tsjcGtd5pPfyTh2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});